version: '3'

services:


  minio:
    image: minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: minio
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    ports:
      - "9000:9000"
      - "39223:39223"
    healthcheck:
      test: ["CMD", "curl", "-I", "minio:9000/minio/health/ready"]
      interval: 5s
      timeout: 30s
      retries: 10
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: cjKMqPAaGfpnsIdRzNZG
      MINIO_ROOT_PASSWORD: WjNFiKfpZAVBDScjhp6w4KzFSy7jRkuB50EhoVl3
    command: server /data --console-address ":39223"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 cjKMqPAaGfpnsIdRzNZG WjNFiKfpZAVBDScjhp6w4KzFSy7jRkuB50EhoVl3;
      /usr/bin/mc mb minio/my-bucket;
      /usr/bin/mc policy set public minio/my-bucket;
      exit 0;
      "

  whisperx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisperx
    image: whisperx:latest
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1", "--timeout", "0", "app.main:app", "-k", "uvicorn.workers.UvicornWorker"]
    ports:
      - "8001:8000"
