version: '3'

services:


  minio:
    image: minio/minio:my
    container_name: minio
    restart: unless-stopped
    volumes:
      - /volumes/minio/data:/data
      - /volumes/minio/config:/root/.minio
    ports:
      - "9000:9000"
      - "39223:39223"
    healthcheck:
      test: ["CMD", "curl", "-I", "minio:9000/minio/health/ready"]
      interval: 5s
      timeout: 30s
      retries: 10
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":39223"


  whisperx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisperx
    image: whisperx:latest
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1", "--timeout", "0", "app.main:app", "-k", "uvicorn.workers.UvicornWorker"]
    ports:
      - "8001:8000"
